// Records the raw-input trace used by tools/oracle/test_features.js (feature parity with the prototype).
// Run once:  node tools/oracle/make_raw_trace.js > tools/oracle/fixtures/raw_trace.js
// Deterministic (LCG, fixed seeds). Each step is one second of one player:
//   [x, y, z, yaw, health, maxHealth, food, light, sky, sneak, sprint, held, encl, night,
//    hurt, places, torches, dealt, [d0, seen0, d1, seen1, ...]]
// held is an index into HELD below ('weird' exercises the unknown-class fallback to 'other').
'use strict'
const HELD = ['melee', 'ranged', 'tool', 'block', 'food', 'light', 'other', 'weird']
let seed = 20260927
function rnd () { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed / 0x7fffffff }
function r3 (v) { return Math.round(v * 1000) / 1000 }

const sessions = []
for (let s = 0; s < 3; s++) {
  const steps = []
  let x = s * 100, z = -s * 50, y = s === 1 ? 20 : 70, yaw = 90 * s, hp = 20
  const maxHp = s === 2 ? 40 : 20
  for (let t = 0; t < 400; t++) {
    const ang = rnd() * 2 * Math.PI
    const sp = rnd() < 0.2 ? 0 : rnd() * 5.8
    x += Math.cos(ang) * sp; z += Math.sin(ang) * sp
    y += (rnd() - 0.5) * (s === 1 ? 3 : 0.6)
    if (t === 150 || t === 300) { x += 500; z -= 400 } // teleports (motion ignored for that second)
    yaw = yaw + (rnd() - 0.5) * 200
    if (yaw > 400) yaw -= 720
    if (yaw < -400) yaw += 720
    const hurt = rnd() < 0.04 ? 1 : 0
    hp = hurt ? Math.max(1, hp - 1 - Math.floor(rnd() * 6)) : Math.min(maxHp, hp + 0.25)
    if (s === 0 && t === 200) hp = 0 // a death second
    const places = rnd() < 0.08 ? 1 + Math.floor(rnd() * 3) : 0
    const torches = places && rnd() < 0.35 ? 1 : 0
    const dealt = rnd() < 0.1 ? r3(rnd() * 14) : 0
    const hs = []
    const nh = Math.floor(rnd() * 6)
    for (let k = 0; k < nh; k++) { hs.push(r3(rnd() * 40)); hs.push(rnd() < 0.5 ? 1 : 0) }
    steps.push([r3(x), r3(y), r3(z), r3(yaw), r3(hp), maxHp, Math.floor(rnd() * 21), Math.floor(rnd() * 16),
      rnd() < 0.5 ? 1 : 0, rnd() < 0.15 ? 1 : 0, rnd() < 0.3 ? 1 : 0, Math.floor(rnd() * HELD.length),
      Math.floor(rnd() * 10), rnd() < 0.4 ? 1 : 0, hurt, places, torches, dealt, hs])
  }
  sessions.push(steps)
}
process.stdout.write('// Recorded raw inputs for tools/oracle/test_features.js. Generated by tools/oracle/make_raw_trace.js; do not edit.\n')
process.stdout.write('var PNE_ORA_FIX_HELD = ' + JSON.stringify(HELD) + '\n')
process.stdout.write('var PNE_ORA_FIX_TRACE = ' + JSON.stringify(sessions) + '\n')
