"""
gen_sounds_json.py: writes the Resonance resource-pack data and the server catalog from the verified manifest
(tools/resonance/manifest.json, written by verify.py --install), in one run:

  overrides/kubejs/assets/pne/sounds.json                one sound event per variant, key res.<slug>.<cls>.vNN, with
                                                         attenuation_distance per layer (whispers 32, director layers
                                                         128, tells 24), stream only for files > 10 s, preload for L7
  overrides/kubejs/assets/pne/lang/en_us.json            the subtitles (subtitles.pne.res.<slug>)
  overrides/kubejs/server_scripts/pne_res_catalog.js     PNE_RES_CATALOG in the exact IMPLEMENTATION.md section 5 layout

    python tools/resonance/gen_sounds_json.py                     generate from tools/resonance/manifest.json
    python tools/resonance/gen_sounds_json.py --check             compare what would be generated with the files on disk
    python tools/resonance/gen_sounds_json.py --out-root DIR      write under DIR instead of the repo (tests)
    python tools/resonance/gen_sounds_json.py --empty             write the empty catalog only (no assets yet)

Nothing is written when the manifest records a failing gate, or when it lists an asset of a class that does not
ship (render.ships: the stereo beds, lead decision 1.3, IMPLEMENTATION.md section 5). The build folder's manifest
(tools/resonance/out/manifest.json) lists the beds and is therefore refused; verify.py --install writes the shipped
manifest this script reads by default.
"""
import argparse
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
MANIFEST = os.path.join(HERE, 'manifest.json')
SPEC = os.path.join(HERE, 'spec', 'layers.json')
REL_SOUNDS = os.path.join('overrides', 'kubejs', 'assets', 'pne', 'sounds.json')
REL_LANG = os.path.join('overrides', 'kubejs', 'assets', 'pne', 'lang', 'en_us.json')
REL_CATALOG = os.path.join('overrides', 'kubejs', 'server_scripts', 'pne_res_catalog.js')
CATALOG_PREFIX = 'var PNE_RES_CATALOG = '
HEADER = ('// priority: 90\n'
          '// Generated by tools/resonance/gen_sounds_json.py from the verified manifest. Do not edit by hand.\n')
EMPTY = {'events': {}, 'gen': 'empty', 'pools': {}, 'v': 1}


def r2(x):
    v = round(float(x), 2)
    if v != v or v in (float('inf'), float('-inf')):
        raise ValueError('non-finite number in the catalog')
    return v + 0.0


def catalog_text(cat):
    return HEADER + CATALOG_PREFIX + json.dumps(cat, sort_keys=True) + '\n'


def build(man, man_sha, spec):
    events = {}
    pools = {}
    sounds = {}
    lang = {}
    for key in sorted(man['assets']):
        e = man['assets'][key]
        lay = spec['layers'][e['layer']]
        ev = e['event']
        events[ev] = {
            'layer': e['layer'], 'cls': e['cls'], 'lufs': r2(e['metrics']['lufs_i']), 'mmax': r2(e['metrics']['lufs_m_max']),
            'dur': r2(e['dur']), 'cat': e['cat'], 'comfort': bool(e['comfort']), 'normal': bool(e['normal']),
            'att': int(e['att']), 'stream': bool(e['stream']), 'lf': bool(e['lf']), 'reserve': bool(e['reserve']),
            'amb': bool(e['amb']),
        }
        pools.setdefault('%s.%s' % (e['slug'], e['cls']), []).append(ev)
        snd = {'name': 'pne:' + e['file'][:-len('.ogg')], 'attenuation_distance': int(e['att'])}
        if e['stream']:
            snd['stream'] = True
        if e.get('preload'):
            snd['preload'] = True
        entry = {'sounds': [snd]}
        if e.get('subtitle'):
            entry['subtitle'] = e['subtitle']
            lang[e['subtitle']] = lay['subtitle_text']
        sounds[e['key']] = entry
    for p in pools:
        pools[p].sort()
    cat = {'events': events, 'gen': man_sha[:12], 'pools': pools, 'v': 1}
    return cat, sounds, lang


def json_text(obj):
    return json.dumps(obj, indent=2, sort_keys=True) + '\n'


def outputs(manifest_path, spec_path):
    with open(manifest_path, 'rb') as f:
        raw = f.read().replace(b'\r\n', b'\n')   # the gen hash must not depend on a CRLF checkout
    man = json.loads(raw.decode('utf-8'))
    if not man.get('summary', {}).get('pass'):
        raise SystemExit('the manifest records failing gates (%s): nothing generated' % ', '.join(man.get('summary', {}).get('failed', [])))
    with open(spec_path, encoding='utf-8') as f:
        spec = json.load(f)
    sys.path.insert(0, HERE)
    import render as R   # the spec helpers (ships); imported here so --empty needs nothing beyond the stdlib
    held = sorted(k for k, e in man['assets'].items() if e.get('amb') or not R.ships(spec, e['layer'], e['cls']))
    if held:
        raise SystemExit('the manifest lists %d asset(s) of classes that do not ship (%s ...): nothing generated. No stereo bed '
                         'ships (lead decision 1.3); verify.py --install writes the shipped manifest' % (len(held), ', '.join(held[:3])))
    cat, sounds, lang = build(man, hashlib.sha256(raw).hexdigest(), spec)
    return {REL_SOUNDS: json_text(sounds), REL_LANG: json_text(lang), REL_CATALOG: catalog_text(cat)}


def read_catalog(path):
    """Parse a catalog file the way IMPLEMENTATION.md section 5 promises: line 3, strict JSON."""
    with open(path, encoding='utf-8', newline='') as f:
        lines = f.read().replace('\r\n', '\n').split('\n')
    line = lines[2]
    if not line.startswith(CATALOG_PREFIX):
        raise ValueError('line 3 does not start with %r' % CATALOG_PREFIX)
    return json.loads(line[len(CATALOG_PREFIX):]), lines


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--manifest', default=MANIFEST)
    ap.add_argument('--spec', default=SPEC)
    ap.add_argument('--out-root', default=ROOT)
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--empty', action='store_true')
    args = ap.parse_args(argv)
    if args.empty:
        files = {REL_CATALOG: catalog_text(EMPTY)}
    else:
        files = outputs(args.manifest, args.spec)
    bad = 0
    for rel, text in sorted(files.items()):
        path = os.path.join(args.out_root, rel)
        if args.check:
            try:
                with open(path, encoding='utf-8', newline='') as f:
                    same = f.read().replace('\r\n', '\n') == text
            except OSError:
                same = False
            if not same:
                bad += 1
                print('  FAIL  %s is not what gen_sounds_json.py generates from the manifest' % rel.replace(os.sep, '/'))
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        print('wrote %s' % rel.replace(os.sep, '/'))
    if args.check:
        print(('PASS' if not bad else 'FAIL') + ' gen_sounds_json --check: %d file(s) %s' % (len(files), 'up to date' if not bad else 'stale'))
    return 1 if bad else 0


if __name__ == '__main__':
    sys.exit(main())
